# Generated by Django 3.1.4 on 2020-12-06 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_abstract'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='promote',
            field=models.BooleanField(default=False, verbose_name='promote'),
        ),
    ]
